#Function for calculating delta delta Ct

#' Delta Delta Ct calculation
#'
#' Subtracts the delta Ct values from a control condition from the delta Ct values of experimental condition
#'
#' @return vector
#' @import tidyverse
#' @param dCt vector of dCt values generated by dCt()
#'
#' @examples
#' delta_Ct_values <- dCt(df)
#'
#' @export
#'
